/* tslint:disable:object-literal-sort-keys */
const res = {
    applicant: {
      id: 1,
      company: {
        id: 1,
        name: 'Marvel',
        locked: false,
        // tslint:disable-next-line:max-line-length
        description: 'Marvel Worldwide Inc. (ofte kalt Marvel Comics) er et amerikansk forlag for tegneserier og utgiver av andre media. I 2009 ble moderselskapet Marvel Entertainment kjøpt opp av Walt Disney Company.\n\nForlaget startet som Timely Publications i 1939 før det ble kjent som Atlas Comics på 1950-tallet. I 1961 revolusjonerte Marvel, ledet ann av redaktør Stan Lee, superhelt-sjangeren med et fokus på historier og karakterer tilpasset et bredere publikum. Fantastic Four ble skapt i 1961 og serien var ulik de erketypiske superheltene fra andre forlag.\n\nBlant Marvel sine mest kjente superhelter finner man Spider-Man, Iron Man, Captain America, Wolverine, Thor, Hulk og Ant-Man i tillegg til superheltgrupper som Avengers, Guardians of the Galaxy, Fantastic Four og X-Men. De fleste av de fiktive karakterene lever i en verden kjent som Marvel-universet. Universet har flere steder som er basert på ekte byer. Spider-Man, Fantastic Four, Avengers, Daredevil og Doctor Strange bor i New York mens X-Men har sitt tilholdssted i Salem Center.',
        logo: 'https://res.cloudinary.com/wadev/image/upload/v1525698664/companylogo/1200px-MarvelLogo.svg_ca34oz.png',
        zip: '90210',
        city: 'Beverly Hills',
        state: 'California',
        countryCode: 'US',
        website: 'www.Marvel.com',
        phone: '100100100',
        email: 'contact@marvelfake.com',
        guid: '54af054d-eb86-479c-abff-0db6c54cc26a',
        isRecruiter: false,
        havePaid: true,
        displayCharts: false,
        numberOfQueries: 0,
        numberOfPokes: 0,
        premiumEndDate: null,
        payStatus: 2,
        plannedHires: '10000',
      },
      direction: 0,
      approved: true,
      created: '14-05-2018',
      user: {
        deleteRequested: '0001-01-01T00:00:00',
        id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
        username: 'bw@marvel.com',
        firstName: 'Black',
        lastName: 'Widow',
        picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
        birthday: '05-05-1928',
        address: null,
        city: null,
        zip: null,
        country: null,
        webpage: null,
        currentRole: null,
        motto: null,
        // tslint:disable-next-line:max-line-length
        experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
        region: null,
        phone: null,
        registrationDate: '14-05-2018',
        driversLicense: false,
        setupDone: true,
        driversLisenceText: 'No Driver Licence',
        contactEmail: 'bw@marvel.com',
        availability: null,
        salary: null,
        startPage: null,
        isInterestedInJobOffer: true,
        disableEmails: false,
        userType: 0,
      },
      isFavorite: false,
      thumbsStatus: 0,
      rejected: false,
      listings: [
        {
          id: 5,
          created: '14-05-2018',
          listing: {
            id: 6,
            title: 'Testing one more',
            jobTitle: '',
            description: '',
            published: null,
          },
          user: {
            deleteRequested: '0001-01-01T00:00:00',
            id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
            username: 'bw@marvel.com',
            firstName: 'Black',
            lastName: 'Widow',
            picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
            birthday: '05-05-1928',
            address: null,
            city: null,
            zip: null,
            country: null,
            webpage: null,
            currentRole: null,
            motto: null,
            // tslint:disable-next-line:max-line-length
            experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
            region: null,
            phone: null,
            registrationDate: '14-05-2018',
            driversLicense: false,
            setupDone: true,
            driversLisenceText: 'No Driver Licence',
            contactEmail: 'bw@marvel.com',
            availability: null,
            salary: null,
            startPage: null,
            isInterestedInJobOffer: true,
            disableEmails: false,
            userType: 0,
          },
          applicationText: 'SuperNinja coming here! :) ',
        },
        {
          id: 4,
          created: '14-05-2018',
          listing: {
            id: 5,
            title: 'Testing here booois',
            jobTitle: '',
            description: '',
            published: null,
          },
          user: {
            deleteRequested: '0001-01-01T00:00:00',
            id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
            username: 'bw@marvel.com',
            firstName: 'Black',
            lastName: 'Widow',
            picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
            birthday: '05-05-1928',
            address: null,
            city: null,
            zip: null,
            country: null,
            webpage: null,
            currentRole: null,
            motto: null,
            // tslint:disable-next-line:max-line-length
            experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
            region: null,
            phone: null,
            registrationDate: '14-05-2018',
            driversLicense: false,
            setupDone: true,
            driversLisenceText: 'No Driver Licence',
            contactEmail: 'bw@marvel.com',
            availability: null,
            salary: null,
            startPage: null,
            isInterestedInJobOffer: true,
            disableEmails: false,
            userType: 0,
          },
          applicationText: 'Testing some shite! :) ',
        },
        {
          id: 1,
          created: '14-05-2018',
          listing: {
            id: 2,
            title: 'With Skills',
            jobTitle: '',
            description: '',
            published: null,
          },
          user: {
            deleteRequested: '0001-01-01T00:00:00',
            id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
            username: 'bw@marvel.com',
            firstName: 'Black',
            lastName: 'Widow',
            picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
            birthday: '05-05-1928',
            address: null,
            city: null,
            zip: null,
            country: null,
            webpage: null,
            currentRole: null,
            motto: null,
            // tslint:disable-next-line:max-line-length
            experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
            region: null,
            phone: null,
            registrationDate: '14-05-2018',
            driversLicense: false,
            setupDone: true,
            driversLisenceText: 'No Driver Licence',
            contactEmail: 'bw@marvel.com',
            availability: null,
            salary: null,
            startPage: null,
            isInterestedInJobOffer: true,
            disableEmails: false,
            userType: 0,
          },
          applicationText: 'Some Text here man! :) ',
        },
        {
          id: 3,
          created: '14-05-2018',
          listing: {
            id: 4,
            title: 'Need a spy man',
            jobTitle: 'SpyLadt',
            description: 'SPY MAN',
            published: '14-05-2018',
          },
          user: {
            deleteRequested: '0001-01-01T00:00:00',
            id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
            username: 'bw@marvel.com',
            firstName: 'Black',
            lastName: 'Widow',
            picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
            birthday: '05-05-1928',
            address: null,
            city: null,
            zip: null,
            country: null,
            webpage: null,
            currentRole: null,
            motto: null,
            // tslint:disable-next-line:max-line-length
            experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
            region: null,
            phone: null,
            registrationDate: '14-05-2018',
            driversLicense: false,
            setupDone: true,
            driversLisenceText: 'No Driver Licence',
            contactEmail: 'bw@marvel.com',
            availability: null,
            salary: null,
            startPage: null,
            isInterestedInJobOffer: true,
            disableEmails: false,
            userType: 0,
          },
          applicationText: 'Im a spy woman?',
        },
        {
          id: 2,
          created: '14-05-2018',
          listing: {
            id: 3,
            title: 'Testing',
            jobTitle: 'LOLOL',
            description: 'Some text for description',
            published: null,
          },
          user: {
            deleteRequested: '0001-01-01T00:00:00',
            id: 'fc1e082d-b52d-41c8-929c-dbe308164226',
            username: 'bw@marvel.com',
            firstName: 'Black',
            lastName: 'Widow',
            picture: 'https://res.cloudinary.com/wadev/image/upload/v1526294478/profile/black-widow-2_ylicl8.jpg',
            birthday: '05-05-1928',
            address: null,
            city: null,
            zip: null,
            country: null,
            webpage: null,
            currentRole: null,
            motto: null,
            // tslint:disable-next-line:max-line-length
            experience: 'After Russian scientist Anton Vanko left Russia to work with Iron Man (Tony Stark), Natasha’s superiors sent her and another operative, Boris Turgenov, to assassinate both men. When Turgenov stole Vanko’s Crimson Dynamo armor, both Turgenov and Vanko died in battle but Natasha escaped. Later, feigning repentance, she romanced Stark long enough to steal his experimental anti-gravity ray. With it, she performed several acts of sabotage against the USA until Iron Man deactivated the device. Her cover blown, she romanced and manipulated the outlaw archer Hawkeye (Clint Barton) into working with her, helping him enhance his archery arsenal with high-tech arrows. The pair attacked Iron Man, who deflected one of Hawkeye’s explosive arrows, its impact felling Natasha and ending the battle when Hawkeye rushed her to safety. While recovering, she persuaded Hawkeye to attack her superiors’ next target, Williams Innovations, but Spider-Man’s intervention drove Hawkeye away. The idealistic Hawkeye’s growing influence upon Natasha led her to rebel against her communist superiors, who extorted her into returning to action with a new costume and weapons, but she and Hawkeye again failed against Iron Man.\n\nMore on Marvel.com: http://marvel.com/universe/Black_Widow_(Natasha_Romanova)#ixzz5FTIM9vVW',
            region: null,
            phone: null,
            registrationDate: '14-05-2018',
            driversLicense: false,
            setupDone: true,
            driversLisenceText: 'No Driver Licence',
            contactEmail: 'bw@marvel.com',
            availability: null,
            salary: null,
            startPage: null,
            isInterestedInJobOffer: true,
            disableEmails: false,
            userType: 0,
          },
          applicationText: 'Super SPy',
        },
      ],
      languages: [
        {
          id: 13,
          name: 'ru',
          oral: 'Native or bi-lingual',
          written: 'Fluent',
        },
        {
          id: 14,
          name: 'en',
          oral: 'Native or bi-lingual',
          written: 'Fluent',
        },
      ],
      userskills: [
        {
          id: 13,
          skillId: 9,
          level: 4,
          favourite: true,
          lastUsed: '2018',
          frequency: 0,
          timestamp: null,
          status: true,
          verified: false,
        },
      ],
      experiences: [],
      userskillExperiences: [],
    },
    selected: false,
    skills: [
      {
        id: 1,
        title: 'Cloning',
        tags: '[]',
        inactive: false,
      },
      {
        id: 2,
        title: 'Elasticity',
        tags: '[]',
        inactive: false,
      },
      {
        id: 3,
        title: 'Electrical absorption',
        tags: '[]',
        inactive: false,
      },
      {
        id: 4,
        title: 'Enhanced hearing',
        tags: '[]',
        inactive: false,
      },
      {
        id: 5,
        title: 'Enhanced memory',
        tags: '[]',
        inactive: false,
      },
      {
        id: 6,
        title: 'Enhanced strength',
        tags: '[]',
        inactive: false,
      },
      {
        id: 7,
        title: 'Flight',
        tags: '[]',
        inactive: false,
      },
      {
        id: 8,
        title: 'Freezing',
        tags: '[]',
        inactive: false,
      },
      {
        id: 9,
        title: 'Speed',
        tags: '[]',
        inactive: false,
      },
    ],
  }

export default class Candidate {
    public loadProps() {
      return res
    }
  }
